version: '3.8'

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongo1_data:/data/db
    restart: always

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongo2_data:/data/db
    restart: always

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27019:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongo3_data:/data/db
    restart: always
volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
